AC-519 : Kotlin version error, causing build to fail: Fixed
> Task :openmrs-client:transformDexArchiveWithExternalLibsDexMergerForDebug
D8: Cannot fit requested classes in a single dex file (# methods: 65585 > 65536)
> Task :openmrs-client:transformDexArchiveWithDexMergerForDebug FAILED
java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
The number of method references in a .dex file cannot exceed 64K.
Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html